# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56f35f86f3e78d5008bc3fd3b7a2123e8bd69ab8fe1d6864499315893c52890c345b5b9efb8cec22455ddbe195848cb7f4fd516c740cd6bcb26a0e3f381b460c

test:
  secret_key_base: 9402a11893c8fe91ddb10bbc7136e32cf17c47cbb1b03c7b1f33e78e13937f1300c4be61745e2ea052a5fac8d29cb36112bebc3406dda1b712bfd3853d004347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
